#
# SPDX-License-Identifier: GPL-2.0
#
# @author Ammar Faizi <ammarfaizi2@gmail.com> https://www.facebook.com/ammarfaizi2
# @license GNU GPL-2.0
# @link https://github.com/ammarfaizi2/bluetea
#
# Copyright (C) 2021  Ammar Faizi
#

DEP_DIRS += $(BASE_DEP_DIR)/src/bluetea/tests

THIS_TEST_NAME :=
THIS_TEST_BIN :=
THIS_TEST_OBJ :=
THIS_TEST_EXTRA :=

include $(BASE_DIR)/src/bluetea/tests/001_string/Makefile
include $(BASE_DIR)/src/bluetea/tests/002_getopt/Makefile
include $(BASE_DIR)/src/bluetea/tests/003_queue/Makefile
include $(BASE_DIR)/src/bluetea/tests/004_mutex/Makefile

