#
# SPDX-License-Identifier: GPL-2.0
#
# @author Ammar Faizi <ammarfaizi2@gmail.com> https://www.facebook.com/ammarfaizi2
# @license GNU GPL-v2
#
# TeaVPN2 - Fast and Free VPN Software
#

INCLUDE_DIR	+= -I$(BASE_DIR)/tests
DEP_DIRS	+= $(BASE_DEP_DIR)/src/teavpn2/tests
TEST_OBJ	:=
TEST_FWOBJ	:= $(BASE_DIR)/tests/libteatest.so



TEST_LIB_LDFLAGS := -L$(BASE_DIR)/tests -lteatest -L$(BASE_DIR) -lteavpn2
LD_LIBRARY_PATH	:= $(LD_LIBRARY_PATH):$(BASE_DIR):$(BASE_DIR)/tests
export LD_LIBRARY_PATH


###################################################################
#
# Build Tea Test (Unit Test Framework for C project)
#
###################################################################
$(BASE_DIR)/tests/teatest.o: $(BASE_DIR)/tests/teatest.c
	$(S)echo "   CC		" "$(@:$(BASE_DIR)/%=%)"
	$(Q)$(CC) $(DEPFLAGS) $(CFLAGS) -Wno-missing-noreturn -c $(@:.o=.c) -o $(@)


TEST_OBJ += $(BASE_DIR)/tests/teatest.o
-include $($(BASE_DIR)/tests/teatest.o:$(BASE_DIR)/%.so=$(BASE_DEP_DIR)/%.d)



$(TEST_FWOBJ): $(BASE_DIR)/tests/teatest.o $(SHARED_BIN)
	$(S)echo "   LD		" "$(@:$(BASE_DIR)/%=%)"
	$(Q)$(LD) $(DEPFLAGS) $(CFLAGS) -shared -o $(@) $(<) $(SHARED_BIN)
##################################################################


include $(BASE_DIR)/tests/001_string/Makefile


$(TESTS): $(TEST_FWOBJ)

test: $(TEST_OBJ) $(TESTS)



clean_test:
	$(Q)rm -vf $(TEST_OBJ)


.PHONY: test clean_test
