
#ifndef TEAVPN2__SERVER__SOCK__TCP_INLINE_FUNCTIONS_H
#define TEAVPN2__SERVER__SOCK__TCP_INLINE_FUNCTIONS_H

#include <teavpn2/server/sock/tcp.h>


#endif /* #ifndef TEAVPN2__SERVER__SOCK__TCP_INLINE_FUNCTIONS_H */
