# SPDX-License-Identifier: GPL-2.0
#
# @author Ammar Faizi <ammarfaizi2@gmail.com> https://www.facebook.com/ammarfaizi2
# @license GNU GPL-v2
#
# TeaVPN2 - Fast and Free VPN Software
#

include $(BASE_DIR)/src/ext/criterion/Makefile
include $(BASE_DIR)/src/ext/inih/Makefile
include $(BASE_DIR)/src/ext/openssl_1.1.1j/Makefile

# __execute_make_io_uring:
# 	+$(Q)cd $(BASE_DIR)/src/ext/liburing-2.0 && $(MAKE) --no-print-directory;

# __clean_io_uring:
# 	+$(Q)cd $(BASE_DIR)/src/ext/liburing-2.0 && $(MAKE) --no-print-directory clean;

# LIB_LDFLAGS	+= -L$(BASE_DIR)/src/ext/liburing-2.0/src -luring
# SHARED_LIB	+= $(BASE_DIR)/src/ext/liburing-2.0/src/liburing.so.2.0.0

# $(BASE_DIR)/src/ext/liburing-2.0/src/liburing.so.2.0.0: __execute_make_io_uring

# clean_ext: __clean_io_uring
