#
# SPDX-License-Identifier: GPL-2.0
#
# @author Ammar Faizi <ammarfaizi2@gmail.com> https://www.facebook.com/ammarfaizi2
# @license GNU GPL-2.0
# @link https://github.com/ammarfaizi2/bluetea
#
# Makefile for BlueTea C framework (lib)
#
# Copyright (C) 2021  Ammar Faizi
#


include $(BASE_DIR)/src/bluetea/lib/string/Makefile


DEP_DIRS += $(BASE_DEP_DIR)/src/bluetea/lib
BLUETEA_CC_OBJ += \
	$(BASE_DIR)/src/bluetea/lib/arena.o \
	$(BASE_DIR)/src/bluetea/lib/getopt.o \
	$(BASE_DIR)/src/bluetea/lib/queue.o \
	$(BASE_DIR)/src/bluetea/lib/string.o
