#
# SPDX-License-Identifier: GPL-2.0
#
# @author Ammar Faizi <ammarfaizi2@gmail.com> https://www.facebook.com/ammarfaizi2
# @license GNU GPL-2.0
#
# Makefile for libraries on BlueTea C framework
#
# Copyright (C) 2021  Ammar Faizi
#

DEP_DIRS += $(BASE_DEP_DIR)/src/bluetea/lib
FBT_CC_OBJ += \
	$(BASE_DIR)/src/bluetea/lib/arena.o \
	$(BASE_DIR)/src/bluetea/lib/getopt.o \
	$(BASE_DIR)/src/bluetea/lib/string.o
