#
# SPDX-License-Identifier: GPL-2.0
#
# @author Ammar Faizi <ammarfaizi2@gmail.com> https://www.facebook.com/ammarfaizi2
# @license GPL-2.0
#
# Copyright (C) 2021  Ammar Faizi
#

DEP_DIRS	+= $(BASE_DEP_DIR)/src/ext/inih
OBJ_CC		+= $(BASE_DIR)/src/ext/inih/inih.o
