#
# SPDX-License-Identifier: GPL-2.0
#
# @author Ammar Faizi <ammarfaizi2@gmail.com> https://www.facebook.com/ammarfaizi2
# @license GNU GPL-v2
#
# TeaVPN2 - Fast and Free VPN Software
#

INCLUDE_DIR	+= -I$(BASE_DIR)/src/ext
DEP_DIRS	+= $(BASE_DEP_DIR)/src/teavpn2/ext

include $(BASE_DIR)/src/ext/inih/Makefile
include $(BASE_DIR)/src/ext/openssl_1.1.1j/Makefile
