name: Build Linux

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - cc: gcc
            cxx: g++
          - cc: clang
            cxx: clang++

    env:
      V: 1
      BAN_WARN: 1

    steps:
    - name: Checkout source
      uses: actions/checkout@v2

    - name: Install tools
      run: |
        sudo apt-get install clang gcc g++ make libgtk-3-dev -y;

    - name: Show tools version
      run: |
        ${{matrix.cc}} --version;
        ${{matrix.cxx}} --version;
        make --version;

    - name: Build
      run: |
        ./configure --cc=${{matrix.cc}} --cxx=${{matrix.cxx}};
        make -j$(nproc);

    - name: Build with GUI
      run: |
        ./configure --cc=${{matrix.cc}} --cxx=${{matrix.cxx}} --gui;
        make -j$(nproc);
